module:
  hugoVersion:
    min: 0.81.0
  imports:
    - path: github.com/hugoinaction/Resources
      mounts:
        - source: assets
          target: assets
    - path: github.com/hugoinaction/hugo-debug-utils
    - path: github.com/hugoinaction/AcmeShared
    - path: github.com/gohugoio/hugo-mod-jslibs/instantpage
