module:
  hugoVersion:
    min: 0.86.0
  imports:
    - path: github.com/hugoinaction/AcmeSupport
      mounts:
        - source: assets
          target: assets
    - path: github.com/hugoinaction/hugo-debug-utils
